### PR TITLE
Upgrading min python version to >= 3.7

### PR DESCRIPTION
**Pull request by tushar5526**
Related to #360 
- Update GHAs to support python >= 3.7
- Bump skia to >= 85.0 and update base.py for the new skia version
- Update setup.py

### CODE REVIEW

**Comment by tushar5526** [comment]
@ziyaointl Should we run the linter and pytest for each python version?

**Comment by tushar5526** [comment]
@ziyaointl I have saved a draft for the next release as well, do take a look at it and share your thoughts.

**Comment by tushar5526** [comment]
We should make the release after merging "enhancing skia" PR.

**Comment by ziyaointl** [comment]
@tushar5526 I think running linter and the formatter using the lowest supported python version (3.7) is ok, since newer versions of Python usually don't break backward compatibility from my experience, but accidentally using a feature only supported in newer versions means we break the library for anyone using lower versions of Python.

**Comment by ziyaointl** [comment]
On publishing to pypi, looks like although I have the permission to release a new version, I do not have the permission to add new maintainers. I will send an email to @abhikpal and @parsoyaarihant on this.

**Comment by ziyaointl** [comment]
nit: I recommend opening multiple PRs for some of the items included in this release (e.g. bumping minimum python version, updating changelog/docs, etc.). This makes changes easy to revert individually if something breaks, and makes the history on master clearer. To track the progress for the release, we can open an issue that includes a checklist.
P.S. tags can be directly pushed to Github without creating a PR
```bash
# Once we have all PRs that we want to include merged to master
git checkout master
git pull
git tag v0.8.0 
git push origin v0.8.0 
```

**Comment by tushar5526** [comment]
I have broken it into multiple PRs

**Comment by tushar5526** [comment]
I will probably update the GHAs to run one after each other |  linters -> pytest -> sanity_tests. If anything fails then we don't have to check further, so we can keep different python version as well.

**Comment by ziyaointl** [comment]
@tushar5526 Yeah that's a good idea!

**Comment by tushar5526** [comment]
I will do it in a different PR this one is good to go.

**Pull request merged**
