### PR TITLE
fix bug #23: Tuple unpacking incompatible with Python 3.4 and less

### PR DESCRIPTION
**Pull request by hx2A**
Simple fix for this bug so the package is backwards compatible.

### CODE REVIEW

**Comment by abhikpal** [comment]
Yep, this doe s fix the issue :) I've merged this to ```develop```

**Comment by jeremydouglass** [comment]
More compatibility in the code base is better... but isn't it the case that p5py will still require minimum 3.5 https://github.com/p5py/p5/issues/41  anyway? At least, as long as it uses things like the [@ matrix multiplication operator](https://www.python.org/dev/peps/pep-0465/) -- as for example in:

https://github.com/p5py/p5/blob/master/p5/pmath/vector.py#L345

**Comment by hx2A** [comment]
@jeremydouglass that is a fair point but I'd argue that the new version is also more readable. Also, if supporting previous versions of Python is important it would be easy to change the few places that use the `@` operator with the numpy matrix multiplication function.

**Comment by jeremydouglass** [comment]
@hx2A -- good points. To be clear, I'm not against this change in #40 -- I agree that more previous Python 3.x version compatibility is better.

**Comment by hx2A** [comment]
@jeremydouglass agreed! I like the new `@` operator also but perhaps if its use in p5py limits Python compatibility then that should be modified also? Replacing it with numpy's matrix multiplication function should suffice.

This project is part of the Google Summer of Code. Are one of you the person working on this?

**Comment by abhikpal** [comment]
> This project is part of the Google Summer of Code. Are one of you the person working on this?

I'm working on this actually. PR #22 already solves the ```np.dot``` / ```@``` issue and it has been merged to the ```develop``` branch. These will be merged to ```master``` soon.

**Comment by hx2A** [comment]
@abhikpal awesome! I'm eager to work with the final result at the end of the summer.

**Comment by abhikpal** [comment]
@hx2A, thanks! You're welcome to test things out and give us feedback over the summer as well :)

**Pull request merged**
