### PR TITLE
Removed pyglet.window.get_platform()

### LINKED ISSUE #10: Sketch window stops refreshing on Mac.
**Test Script:**  [p5-examples/basics/math/sine.py](https://github.com/p5py/p5-examples/blob/master/basics/math/sine.py). The bug affects all sketches.

**Expected behavior:**
sine-correct

**Actual behavior** The sketch window stops refreshing after a couple of frames are drawn when a newer version of Pyglet (1.3b) is installed. 

sine

**Errors produced (if any):** None

**p5 version:**  2b96dfc1d2126867e70bc727d0cc7ffc5da8eabc

**Python version:** 3.6
**Operating System:**  Mac OS

### PR DESCRIPTION
**Pull request by parsoyaarihant**
Fixes #10 .

* I contacted Pyglet community on bitbucket and they said that `platform`. API has been depreciated and will be removed soon : https://bitbucket.org/pyglet/pyglet/issues/175/pyglet-config-error-in-pygletwindowwindow

* Based on the Pyglet community response, I have updated the code accordingly and it works as expected on Mac.

### CODE REVIEW

**Comment by abhikpal** [comment]
Hmm. interesting. This seems to break on my machine (Debian 9 running on a ThinkPad)... The window opens but fails to display anything. I do see some grey boxes occasionally, though. Here's what I get:
pr35

**Comment by parsoyaarihant** [comment]
Can you send your `config` variable when it is working and not working?

**Comment by parsoyaarihant** [comment]
@abhikpal , I have pushed a new commit in this PR. Can you check if this new configuration works on your computer?

**Comment by parsoyaarihant** [comment]
Ping @abhikpal .

**Pull request closed without merging**
