### PR TITLE
Fix issue 60: background() doesn't work in setup.

### PR DESCRIPTION
**Pull request by vaishnavsm**
Please check issue #60 for analysis on the issue.
Two changes made:
1) Function `background()` now returns the color if color is changed as expected
2) Function `background()` now permanently sets the renderer color to the new color. Note that this means that the behavior of the function is now inconsistent! Images can only be set in draw(), due to the mechanics of the renderer, while background color can be set from either draw() or setup().

I shall soon change the renderer to support images as backgrounds in setup() too.

Edit:
**Changed the renderer to be consistent with the color**
In the latest commit, both images and colors can be used in setup and draw.
This has been achieved by simply mimicking the background() function for images, minus checking validity, in the renderer's clear function.

### CODE REVIEW

**Comment by vaishnavsm** [comment]
Commit be14903 changes renderer behavior, so that it is now consistent with color.
Both image and color should work in `setup()` method now.

Further changed the `push_style` CM to support the newly added `background_image` in the renderer.

Code has been checked for potential problems.

**Comment by abhikpal** [comment]
The merge seems to break things:
```    from p5 import *
  File ".../p5py/p5/__init__.py", line 19, in <module>
    from .sketch import *
  File ".../p5py/p5/sketch/__init__.py", line 21, in <module>
    from .userspace import *
  File ".../p5py/p5/sketch/userspace.py", line 29, in <module>
    from .base import Sketch
  File ".../p5py/p5/sketch/base.py", line 32, in <module>
    from .. sketch import renderer
  File ".../p5py/p5/sketch/renderer.py", line 39, in <module>
    from .structure import push_style
ModuleNotFoundError: No module named 'p5.sketch.structure'
```

Reverting the commit for now.

**Comment by vaishnavsm** [comment]
Doh. Silly error. Fixed. Should I open a new PR?

**Comment by abhikpal** [comment]
Yep. Make a new PR.

**Comment by parsoyaarihant** [comment]
This issue is not yet fixed.

**Comment by veziop** [comment]
I am having the same issue, p5.background() doesnt have any effect on the sketch.

**Pull request merged**
