### PR TITLE
Added slack link in contribution.rst

### PR DESCRIPTION
**Pull request by tushar5526**
https://join.slack.com/t/p5py/shared_invite/zt-e8mxhses-b2Vqc~zcU_kC5vCnJqrFxA  : Added this slack invite link in contribution.rst.

### CODE REVIEW

**Comment by Andy-Python-Programmer** [comment]
Hi @tushar5526 if I open this link I get this error: 
IMG_1182

**Comment by parsoyaarihant** [comment]
@tushar5526 can you use the updated invite link? : https://join.slack.com/t/p5py/shared_invite/zt-g9uo4vph-dUVltiE1ixvmjFTCyRlzpQ

**Comment by parsoyaarihant** [comment]
It would be great if you can use a image button as the link. Something like this:

Screenshot 2020-08-02 at 10 31 05 AM

**Comment by Andy-Python-Programmer** [comment]
Yes that link works

**Comment by tushar5526** [comment]
Did that. Thanks :)

**Pull request merged**
