### PR TITLE
formatted the whole code with autopep8

### PR DESCRIPTION
**Pull request by tushar5526**
Related to #255

No merge conflicts and only python files are formatted, .rst and md files are not affected.

Command ran : 
```
find . -name '*.py' -exec autopep8 --in-place --aggressive '{}' \;
```

### CODE REVIEW

**Comment by parsoyaarihant** [comment]
Can you check the linting with pylint? use
pylint `ls -R|grep .py$|xargs`

**Comment by parsoyaarihant** [comment]
I am not sure why your pylint is not running on this PR

**Comment by tushar5526** [comment]
@parsoyaarihant 
It worked after using
```
pylint $(ls -R|grep .py$|xargs)
```

**Comment by tushar5526** [comment]
Greetings.yml is working as it is set to `on : pull_requests` while pylint.yml is set `on: push`

**Comment by tushar5526** [comment]
Pylint was failing on python files inside a directory, as only file names were parsed by `ls -R|grep .py$|xargs`
This works
```
pylint `find . -name '*.py'`   # give the complete path
```

**Comment by parsoyaarihant** [comment]
`pylint `find . -name '*.py'`   # gives the complete path` 
this command is also giving many errors right?

**Comment by tushar5526** [comment]
@parsoyaarihant A lot of warning, and some errors towards the end. Take a look here, I update the pylint.yml so it works fines on github actions [build log](https://github.com/p5py/p5/runs/1072798678?check_suite_focus=true)

**Comment by parsoyaarihant** [comment]
The errors for profiling can be fixed by doing specific imports.
Is there any way to disable naming styles? Such as snake_case naming style?
Arent spaces and tabs handled by autopep8? There are many warnings related to that.

Other errors needs to be fixed manually i think.

**Comment by tushar5526** [comment]
> Is there any way to disable naming styles? Such as snake_case naming style?
> Arent spaces and tabs handled by autopep8? There are many warnings related to that.

we can configure pylint according to it, will look into this. I will be using the #269 for testing for now.

**Comment by tushar5526** [comment]
@parsoyaarihant Take a look at the [logs](https://github.com/p5py/p5/pull/269/checks?check_run_id=1074879993), disabled messages related to conventions, warnings, refactoring and excluded **Profiling** sub dir is not included when we run pylint.

**Comment by parsoyaarihant** [comment]
Because of the recent changes in rendering pipeline, the old tests are facing issues. For now, can we ignore the tests too? I will open another issue to fix the tests. After the tests are updated, we can add back the pylint for that.

**Comment by tushar5526** [comment]
Yes, I wasn't sure about the tests, so left it there. Also, as I have disabled the warnings so pep8 conventions can be checked by this #253

**Comment by tushar5526** [comment]
@parsoyaarihant  Check the new [logs](https://github.com/p5py/p5/runs/1075321259?check_suite_focus=true)
It's probably due to setting up renderer at run time, as initially renderers are set to none. Should I skip the renderer2d and renderer3d files too? 
Other errors seem fixable.

**Comment by tushar5526** [comment]
@parsoyaarihant , tests are setup properly. Skipped some lines in renderer2d and renderer3d to be checked by pylint and it works good.
[Logs](https://github.com/p5py/p5/runs/1075388409?check_suite_focus=true) for ref.

**Comment by parsoyaarihant** [comment]
awesome

**Pull request closed without merging**
