### PR TITLE
Added support for loading images from URLs (fixes #281)

### LINKED ISSUE #281: load_image() doesn't support loading images from URL
I'm opening a PR that adds the functionality (and removes the TODO)

### PR DESCRIPTION
**Pull request by breadsanta**
Fixes #281

### CODE REVIEW

**Comment by breadsanta** [comment]
Not getting my greeting really bums me out.

**Comment by tushar5526** [comment]
Thank you for your first PR then :p

**Comment by tushar5526** [comment]
@breadsanta you can use " Fixes #281" ( without quotes ) in description so that GitHub automatically close the issue whenever your PR is merged !

**Comment by parsoyaarihant** [comment]
Thanks!

**Pull request merged**
