### PR TITLE
formatted the whole project with autopep8

### PR DESCRIPTION
**Pull request by tushar5526**
PEP 8 conventions are not followed in p5py. Ran `autopep8` on p5py.

### CODE REVIEW

**Comment by tushar5526** [comment]
Would be better if you run it on your side, and make the changes. :)

**Comment by parsoyaarihant** [comment]
This is good step. I am checking if we can use Travis CI and for code linting, run tests, profiling, etc.

**Comment by tushar5526** [comment]
> This is good step. I am checking if we can use Travis CI and for code linting, run tests, profiling, etc.
I would be glad to work on tests, and updating docs, etc.

**Comment by parsoyaarihant** [comment]
@tushar5526 . I have added pylint test to the repository. Can you fix the conflicts file for this PR?

**Comment by parsoyaarihant** [comment]
Maybe try to rebase your code with the master branch and run autopep8 again.

**Comment by tushar5526** [comment]
Closing this, already two PRs are there related to this.

**Pull request closed without merging**
